### ISSUE TITLE
Include license file in source distribution

### ISSUE THREAD

**Issue by synapticarbors** [EconForge/dolang.py#3]
It would be helpful to include the `COPYING` file in the source distribution. I'm not sure how to do this with `poetry` (and searching through their issues, it looks like maybe it isn't supported yet).

**Comment by albop** [comment]
Apparently, for now poetry does include the LICENSE file without any extra configuration (cf the beginning of the discussion here). It might be more flexible in the future but for now, I just moved COPYING to LICENSE. I checked, it does get copied. Thanks @synapticarbors
